language: php

# lock distro so new future defaults will not break the build
dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

env:
  - LOGIN=username:password@localhost

install:
  - sudo apt-get -qq update || true # update package list and ignore temporary network errors
  - sudo apt-get --no-install-recommends -qq install -y asterisk
  - sudo cp tests/username.conf /etc/asterisk/manager.d/username.conf
  - sudo /etc/init.d/asterisk reload
  - composer install --no-interaction

script:
  - sudo /etc/init.d/asterisk status || sudo /etc/init.d/asterisk start
  - sudo /etc/init.d/asterisk status || sleep 2
  - vendor/bin/phpunit --coverage-text
